import type { Prisma } from '@prisma/client';
import { basename, extname } from 'node:path';
import { getArtfactFilenameCount, getArtifactUrl, getArtifactUrls } from './artifacts';

// eslint-disable-next-line @typescript-eslint/no-namespace
export namespace Build {
  export enum Status {
    Initialized = 'initialized',
    Accepted = 'accepted',
    Active = 'active',
    Expired = 'expired',
    PostProcessing = 'postprocessing',
    Completed = 'completed'
  }

  export enum Result {
    Success = 'SUCCESS',
    Failure = 'FAILURE',
    Aborted = 'ABORTED'
  }

  export enum Channel {
    Unpublished = 'unpublished',
    Alpha = 'alpha',
    Beta = 'beta',
    Production = 'production'
  }

  export enum Artifact {
    Unknown = 'unknown',
    AAB = 'aab',
    APK = 'apk',
    VersionCode = 'version_code',
    Version = 'version',
    About = 'about',
    PlayListing = 'play-listing',
    PlayListingManifest = 'play-listing-manifest',
    PackageName = 'package_name',
    PublishProperties = 'publish_properties',
    CloudWatch = 'cloudWatch',
    ConsoleText = 'consoleText',
    WhatsNew = 'whats_new',
    HTML = 'html',
    PWA = 'pwa',
    EncryptedKey = 'encrypted_key',
    AssetPackage = 'asset-package',
    AssetPreview = 'asset-preview',
    AssetNotify = 'asset-notify',
    DataSafetyCsv = 'data-safety-csv'
  }

  export function artifactType(key: string): [Artifact, string] {
    const ext = extname(key);
    let file = basename(key);
    let type = Artifact.Unknown;
    if (file === 'cloudWatch') {
      type = Artifact.CloudWatch;
    } else if (ext === 'log') {
      type = Artifact.ConsoleText;
    } else if (ext === 'aab') {
      type = Artifact.AAB;
    } else if (ext === 'apk') {
      type = Artifact.APK;
    } else if (file === 'version_code.txt') {
      type = Artifact.VersionCode;
    } else if (file === 'version.json') {
      type = Artifact.Version;
    } else if (file === 'package_name.txt') {
      type = Artifact.PackageName;
    } else if (file === 'publish-properties.json') {
      type = Artifact.PublishProperties;
    } else if (file === 'about.txt') {
      type = Artifact.About;
    } else if (file === 'whats_new.txt') {
      type = Artifact.WhatsNew;
    } else if (file === 'html.zip') {
      type = Artifact.HTML;
    } else if (file === 'pwa.zip') {
      type = Artifact.PWA;
    } else if (file === 'private_key.pepk') {
      type = Artifact.EncryptedKey;
    } else if (key.match(/asset-package\/.*\.zip/)) {
      type = Artifact.AssetPackage;
      file = 'asset-package/' + file;
    } else if (key.match(/asset-package\/preview\.html/)) {
      type = Artifact.AssetPreview;
      file = 'asset-package/preview.html';
    } else if (key.match(/asset-package\/notify\.json/)) {
      type = Artifact.AssetNotify;
      file = 'asset-package/notify.json';
    } else if (key.match(/play-listing\/index\.html/)) {
      type = Artifact.PlayListing;
      file = 'play-listing/index.html';
    } else if (key.match(/play-listing\/manifest.json/)) {
      type = Artifact.PlayListingManifest;
      file = 'play-listing/manifest.json';
    } else if (key.match(/data_safety\.csv/)) {
      type = Artifact.DataSafetyCsv;
    }

    return [type, file];
  }

  export function artifacts(
    build: Prisma.buildGetPayload<{
      select: {
        targets: true;
        artifact_url_base: true;
        console_text_url: true;
        artifact_files: true;
      };
    }>
  ) {
    const { targets, artifact_url_base: base, artifact_files: files } = build;
    // We need to at least have one artifact or the current Portal will fail to parse the JSON.
    // TODO: Treat these like the others once Portal is fixed.
    const artifacts = {
      [Artifact.Version]: getArtifactUrl(/version\.json/, base, files),
      [Artifact.CloudWatch]: build.console_text_url,
      // We used to return consoleText as the first item that matched "\.log" and we REALLY want console.log
      // which is generated by BuildEngine.  There is a APK_NAME-output.log which doesn't have everything in the log.
      [Artifact.ConsoleText]: getArtifactUrl(/console\.log/, base, files),
      [Artifact.PublishProperties]: getArtifactUrl(/publish-properties\.json/, base, files)
    } as Record<string, string | undefined>;
    if (targets?.match('apk')) {
      artifacts[Artifact.AAB] = getArtifactUrl(/\.aab/, base, files);
      const count = getArtfactFilenameCount(/\.apk/, files);
      if (count > 1) {
        for (const apk of getArtifactUrls(/\.apk/, base, files) ?? []) {
          const matches = apk.match(/-([^.]+)\.apk/);
          artifacts[matches?.at(1) + '-' + Artifact.APK] = apk;
        }
      } else {
        artifacts[Artifact.APK] = getArtifactUrl(/\.apk/, base, files);
      }
      artifacts[Artifact.EncryptedKey] = getArtifactUrl(/_key\.pepk/, base, files);
      artifacts[Artifact.About] = getArtifactUrl(/about\.txt/, base, files);
      artifacts[Artifact.DataSafetyCsv] = getArtifactUrl(/data_safety\.csv/, base, files);
    }

    if (targets?.match('play-listing')) {
      artifacts[Artifact.PlayListing] = getArtifactUrl(/play-listing\/index\.html/, base, files);
      artifacts[Artifact.PlayListingManifest] = getArtifactUrl(
        /play-listing\/manifest\.json/,
        base,
        files
      );
      artifacts[Artifact.VersionCode] = getArtifactUrl(/version_code\.txt/, base, files);
      artifacts[Artifact.PackageName] = getArtifactUrl(/package_name\.txt/, base, files);
      artifacts[Artifact.PublishProperties] = getArtifactUrl(
        /publish-properties\.json/,
        base,
        files
      );
      artifacts[Artifact.WhatsNew] = getArtifactUrl(/whats_new\.txt/, base, files);
    }

    if (targets?.match('play-html')) {
      artifacts[Artifact.HTML] = getArtifactUrl(/html\.zip/, base, files);
    }

    if (targets?.match('pwa')) {
      artifacts[Artifact.PWA] = getArtifactUrl(/pwa\.zip/, base, files);
    }

    if (targets?.match('asset-package')) {
      artifacts[Artifact.AssetPackage] = getArtifactUrl(/asset-package\/.*\.zip/, base, files);
      artifacts[Artifact.PackageName] = getArtifactUrl(/package_name\.txt/, base, files);
      artifacts[Artifact.AssetPreview] = getArtifactUrl(
        /asset-package\/preview\.html/,
        base,
        files
      );
      artifacts[Artifact.AssetNotify] = getArtifactUrl(/asset-package\/notify\.json/, base, files);
    }

    return artifacts;
  }
}
