-- AlterTable
ALTER TABLE `client` MODIFY `created` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `email_queue` MODIFY `created` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `job` MODIFY `created` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `operation_queue` MODIFY `created` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `project` MODIFY `created` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0);

-- AlterTable
ALTER TABLE `release` MODIFY `created` DATETIME(0) NULL DEFAULT CURRENT_TIMESTAMP(0);
