<?php
namespace tests\unit\common\components;
use tests\unit\UnitTestBase;

use common\models\Job;
use common\models\Build;

use tests\unit\fixtures\common\models\JobFixture;
use tests\unit\fixtures\common\models\BuildFixture;

class BuildTest extends UnitTestBase
{
    /**
     * @var \UnitTester
     */
    protected function _before()
    {
    }

    protected function _after()
    {
    }
    public function fixtures()
    {
        return [
            'job' => JobFixture::className(),
            'build' => BuildFixture::className(),
        ];
    }
    /**
     * This method is only here because if I don't put it in, the first test
     * fails because the params isn't loaded.  Don't know why, but this fixed it
     */
    public function testDummy()
    {
        //codecept_debug("Starting Test");
        $this->assertEquals(1,1);
    }
    public function testArtifactTypeTest()
    {
        $this->setContainerObjects();
        $build = Build::findOne(['id' => 11]);
        $s3Key = "testing/jobs/build_scriptureappbuilder_22/1/cloudWatch";
        list ($type, $file) = $build->artifactType($s3Key);
        $this->assertEquals("cloudWatch", $type, " *** Cloud Watch file type not detected");
        $s3Key = "testing/jobs/build_scriptureappbuilder_22/1/play-listing/index.html";
        list ($type, $file) = $build->artifactType($s3Key);
        $this->assertEquals("play-listing", $type, " *** play listing file type not detected");
        $s3Key = "testing/jobs/build_scriptureappbuilder_22/1/version_code.txt";
        list ($type, $file) = $build->artifactType($s3Key);
        $this->assertEquals("version_code", $type, " *** version code file type not detected");
        $s3Key = "testing/jobs/build_scriptureappbuilder_22/1/about.txt";
        list ($type, $file) = $build->artifactType($s3Key);
        $this->assertEquals("about", $type, " *** about file type not detected");
        $s3Key = "testing/jobs/build_scriptureappbuilder_22/1/testproject.apk";
        list ($type, $file) = $build->artifactType($s3Key);
        $this->assertEquals("apk", $type, " *** apk file type not detected");
        $s3Key = "testing/jobs/build_scriptureappbuilder_22/1/testproject.log";
        list ($type, $file) = $build->artifactType($s3Key);
        $this->assertEquals("consoleText", $type, " *** consoleText file type not detected");
    }
    public function testLogFile()
    {
        // We used to return consoleText as the first item that matched "\.log$" and we REALLY want console.log
        // which is generated by BuildEngine.
        $this->setContainerObjects();
        // console.log is toward the beginning of the list
        $build = Build::findOne(['id' => 12]);
        $consoleText = $build->consoleText();
        $this->assertStringEndsWith("console.log", $consoleText, " *** wrong console log");
        // console.log is after APK-output.log
        $build = Build::findOne(['id' => 18]);
        $consoleText = $build->consoleText();
        $this->assertStringEndsWith("console.log", $consoleText, " *** wrong console log");
    }
    public function testHandleArtifact()
    {
        $this->setContainerObjects();
        $build = Build::findOne(['id' => 11]);
        $s3Key = "testing/jobs/build_scriptureappbuilder_22/1/version_code.txt";
        $content = "5";
        $build->handleArtifact($s3Key, $content);
        $this->assertEquals(5, $build->version_code, " *** Wrong version code");
        $this->assertEquals("version_code.txt", $build->artifact_files, " *** Problem adding artifact");
    }
    public function testFindAllRunningByJobId()
    {
        $this->setContainerObjects();
        $builds = Build::findAllRunningByJobId('22');
        $numberOfRunningBuilds = count($builds);
        $this->assertEquals(2, $numberOfRunningBuilds, " *** Incorrect number of active builds");

    }
    public function testArtifactEncoding() {
        $this->setContainerObjects();
        $build = Build::findOne(['id' => 12]);
        $apks = $build->apks();
        $this->assertContains("https://s3-us-west-2.amazonaws.com/sil-appbuilder-artifacts/testing/jobs/build_scriptureappbuilder_22/1/Test%2B1.0.apk", $apks, " *** filename not encoded correctly");
        $playListing = $build->playListing();
        $this->assertContains("https://s3-us-west-2.amazonaws.com/sil-appbuilder-artifacts/testing/jobs/build_scriptureappbuilder_22/1/play-listing/index.html", $playListing, " *** filename not encoded correctly");
    }
}